### ISSUE TITLE
{Tracking] Iree-amd-aie runtime new feature additions

### ISSUE THREAD

**Issue by nirvedhmeshram** [nod-ai/iree-amd-aie#481]
This is a high level issue to keep track of status of ongoing feature additions relating to the runtime side of things.

- [ ] PDI Merging - See https://github.com/nod-ai/iree-amd-aie/issues/380
- [ ] HIP Bring up - Adding a IREE Hal driver which uses the HIP API from XRT https://github.com/Xilinx/XRT/tree/master/src/runtime_src/hip which will be parallel to XRT API.
- [ ] Heterogenous support - Support is being added in upstream IREE to have heterogenous multi-device execution. We will focus on leveraging that to execute models on CPU+AIE devices.
- [ ] Command chaining - The "Command Chaining" for AIE devices is a concept in XRT for efficient batched run of jobs. You add a list of xrt::run objects to a list and can execute the list together. That is more efficient. You can have N number of xrt::run objects in the list, but up to a maximum of 24 of them are bunched together to reduce overhead of ringing bell at mailbox etc. Here is an example https://github.com/Xilinx/mlir-aie/tree/main/programming_examples/basic/vector_scalar_add_runlist . We can have the iree XRT HAL driver do this too. 
 - [ ] Switching to Elf format - Details TBD
